import mongoose, { Schema } from 'mongoose';

const PendaftaranSchema = new Schema({
  calonPesertaDidik: {
    name: String,
    gender: String,
    nisn: String,
    nis: String,
    ijazahNumber: String,
    nik: String,
    birthPlace: String,
    birthDate: Date,
    specialNeeds: String,
    address: String,
    province: String,
    district: String,
    city: String,
    subdistrict: String,
    addressType: String,
    addressPhone: String,
    phone: String,
    email: String,
  },
  schoolOrigin: {
    name: String,
    city: String,
    address: String,
  },
  calonPesertaDidikScore: {
    score: String,
  },
  prestasi: [
    new Schema({
      tipe: String,
      level: String,
      predicate: String,
      activity: String,
      file: new Schema({
        name: String,
        size: Number,
        url: String,
      }),
    }),
  ],
  father: {
    name: String,
    isAlive: String,
    specialNeeds: String,
    birthPlace: String,
    birthDate: Date,
    address: String,
    lastStudy: String,
    job: String,
    income: String,
    addressPhone: String,
    phone: String,
  },
  mother: {
    name: String,
    isAlive: String,
    specialNeeds: String,
    birthPlace: String,
    birthDate: Date,
    address: String,
    lastStudy: String,
    job: String,
    income: String,
    addressPhone: String,
    phone: String,
    String,
  },
  wali: {
    name: String,
    specialNeeds: String,
    birthPlace: String,
    birthDate: Date,
    address: String,
    lastStudy: String,
    addressPhone: String,
    phone: String,
  },
});

export default mongoose.models.Pendaftaran || mongoose.model('Pendaftaran', PendaftaranSchema);
