import NavbarProvider from 'layouts/NavbarProvider';
import Head from 'next/head';

import Img from 'components/base/Img';
import Carousel from 'components/Carousel';
import ReservationForm from 'components/ReservationForm';

import classes from '../styles/Home.module.css';

const CAROUSEL_IMAGES = [
  { name: 'First Image', url: 'carousel-image-1.jpg' },
  { name: 'Second Image', url: 'carousel-image-2.jpg' },
  { name: 'Third Image', url: 'carousel-image-3.jpg' },
];

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarProvider>
        <div className={classes.carouselContainer}>
          <Carousel className={classes.carouselDimension}>
            {CAROUSEL_IMAGES.map((image) => (
              <div key={image.url} className={classes.carouselDimension}>
                <Img
                  src={`/images/${image.url}`}
                  alt={image.name}
                  sizes="(max-width: 560px) 40vw, (max-width: 1200px) 62.5vw, 100vw"
                />
                <figcaption className={classes.imageCaption}>{image.name}</figcaption>
              </div>
            ))}
          </Carousel>
        </div>
        <main className={classes.mainContent}>
          <ReservationForm />
        </main>

        <footer></footer>
      </NavbarProvider>
    </div>
  );
};

export default Home;
